- name: DEBIAN | Install Caddy packages
  apt:
    name: "{{ caddy_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 600
  tags:
    - caddy

- name: DEBIAN | Set capabilities
  capabilities:
    path: /usr/local/bin/caddy
    capability: cap_net_bind_service=+ep
    state: present
  tags:
    - caddy

- include_tasks: custom-build.yml
