- include_tasks: custom-build.yml
  tags:
    - caddy

- name: DEBIAN | Set capabilities
  capabilities:
    path: /usr/local/bin/caddy
    capability: cap_net_bind_service+ep
    state: present
  tags:
    - caddy
