- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - main.yml
  tags:
    - always
    - caddy

- include: "install-{{ ansible_os_family }}.yml"
  tags:
    - caddy

- name: Create log dir
  file:
    path: "{{ caddy_log_path }}"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0750
  tags:
    - caddy

- name: Copy main Caddy config
  template:
    src: caddy.conf.j2
    dest: "{{ caddy_config_path }}/{{ caddy_config_file }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - caddy
    - caddy_config

- meta: flush_handlers

- name: Start and enable Caddy
  service:
    name: "{{ caddy_service_name }}"
    state: started
    enabled: true
  tags:
    - caddy
    - caddy_service
