- name: Include distribution specific variables
  include_vars: "{{ item }}"
  when: ansible_distribution != 'Ubuntu'
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - main.yml
  tags:
    - always
    - caddy

- include: "install-{{ ansible_os_family }}.yml"
  tags:
    - caddy

- name: Create log dir
  file:
    path: "{{ caddy_log_path }}"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0750
  tags:
    - caddy
