- name: systemd daemon reload
  systemd:
    daemon_reload: true
  when: "ansible_facts['service_mgr'] == 'systemd'"

- name: restart caddy
  service:
    name: "{{ caddy_service_name }}"
    state: restarted

- name: reload caddy
  service:
    name: "{{ caddy_service_name }}"
    state: reloaded
