- hosts: all
  become: true

  tasks:
    - import_role:
        name: repo-epel

    - import_role:
        name: caddy

    - name: Test that Caddy is running
      uri:
        url: http://127.0.0.1
        status_code: 200
        return_content: true
      register: result
      until:
        - result.status == 200
        - "'Caddy web server' in result.content"
      retries: 10
      delay: 5
